#Today we are going to draw Nepal
# Flag using python
from turtle import *
bgcolor('white')
pencolor('blue')
pensize(15)
setposition(0,0)  #it will set x,y=0,0
fillcolor('red')
begin_fill()
forward(200)
setposition(200,0)
setposition(70,90)
setposition(200,98)
setposition(0,220)
setposition(0,0)
end_fill()
#this will fill the red color
#now draw stand for flag
penup()
pensize(0)
setposition(-5,230)
pendown()
pencolor('brown')
fillcolor('brown')
begin_fill()
setposition(-5,-240)
forward(-10)
setposition(-15,229)
# now top of stand
forward(20)
setposition(-10,240)
setposition(-25,230)
forward(25)
end_fill()

#now draw the moon and sun
penup()
fillcolor('white')
pencolor('white')
pensize(2)
setpos(25,60)
begin_fill()
for i in range (12) :
 pendown()
 forward(11)
 left(120)
 forward(11)
 right(150)
right(15)
end_fill()
penup()
setpos(30,130)
pendown()
setheading(270)
begin_fill()
circle(20 ,180)
end_fill()
penup()
setpos(30,130)
setheading(10)
pendown()
begin_fill()
for i in range (8):
  forward(10)
  left(120)
  forward(10)
  right(150)
penup()
end_fill()
setpos(50,140)
#now i will write the some text
color('black')
penup()
setposition(0,250)
pendown()
write("Love from D-The Tech Ghost-Nepal",font=("Times New Roman",20,"normal"),align="center")
penup()
setposition(80, -250)
write("Please SUBSCRIBE us:)", font=("Arial Black", 30, "normal"), align="center")
pendown()
hideturtle() 
done()
#Lets run the code                                              

